version: 1
default_environment: dev
project_id: d61f617c-9f51-4775-a39e-90aa6cbf88cb
environments:
- name: dev
- name: staging
- name: prod
plugins:
  extractors:
  - name: tap-csv
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-csv.git
    config:
      csv_files_definition: ./data/extract/csv_files_definition.json
  - name: tap-postgres
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-postgres.git
    settings:
    - name: filter_schemas
      value: [public]
    config:
      host: localhost
      database: elt_meltano
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
    select:
    - '*.*'
  - name: tap-singer-jsonl
    variant: kgpayne
    pip_url: tap-singer-jsonl
    config:
      local:
        folders:
        - ./data/output/$SOURCE/$YEAR/$MONTH/$DAY/public-orders
        - ./data/output/$SOURCE/$YEAR/$MONTH/$DAY/public-order_details
        recursive: true
  loaders:
  - name: target-jsonl
    variant: andyh1203
    pip_url: target-jsonl
    config:
      destination_path: ./data/output/$SOURCE/$YEAR/$MONTH/$DAY/
      do_timestamp_file: true
  - name: target-singer-jsonl
    variant: kgpayne
    pip_url: target-singer-jsonl
    config:
      local:
        folder: ./data/output/$SOURCE/$YEAR/$MONTH/$DAY/
  - name: target-postgres
    variant: transferwise
    pip_url:
      git+https://github.com/transferwise/pipelinewise.git#subdirectory=singer-connectors/target-postgres
    config:
      dbname: elt_meltano
      host: localhost
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      default_target_schema: analytics

jobs:
  - name: extract_csv
    tasks:
      - tap-csv target-singer-jsonl
  - name: extract_postgres
    tasks:
      - tap-postgres target-singer-jsonl
  - name: load_to_postgres
    tasks:
      - tap-singer-jsonl target-postgres
