name: Run pre-commit

on: pull_request

jobs:
  run_pre_commit:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install precommit
        run: pip install pre-commit

      - name: run pre-commit
        run: pre-commit run --all-files